#ifndef	__VFERR_H__
#define __VFERR_H__

#define		VF_BASE_ERR		10000

#define     VF_LOADFINGER_ERR			(VF_BASE_ERR+100)
#define     VF_SAVEFINGER_ERR			(VF_BASE_ERR+200)
#define     VF_IMPORTFINGER_ERR			(VF_BASE_ERR+300)

#define     VF_PROCESS_ERR				(VF_BASE_ERR+400)
#define     VF_EXTRACT_ERR				(VF_BASE_ERR+500)
#define     VF_FEATUREENCODE_ERR		(VF_BASE_ERR+600)
#define     VF_FEATUREDECODE_ERR		(VF_BASE_ERR+700)
#define     VF_VERIFYMATCH_ERR			(VF_BASE_ERR+800)
#define     VF_SAVEFEATURE_ERR			(VF_BASE_ERR+900)
#define     VF_LOADFEATURE_ERR			(VF_BASE_ERR+1000)



#endif